src/napari_omero/plugins/loaders.py
This fixes opening of Z-stack images (single T).
Currently the `get_data_lazy()` returns a different shape of dask array, depending on `sizeT`.
SizeC is not handled here since we are always just getting the data for a single channel.
This is a quick fix, but I would prefer to have `get_data_lazy()` always return a 5D array of shape `(t, c, z, y, x)` to be consistent with the ome-zarr spec.
This will avoid having to check which dimensions are which elsewhere.
=> Fix opening of Z-stack, single-T images

src/napari_omero/widgets/gateway.py
the SessionsStore.ctx `AttributeError` in https://github.com/tlambert03/napari-omero/issues/2#issuecomment-649595252
was caused by me incorrectly using the timeout argument (and omero-py failing to handle the exception).  This PR fixes the `store.create()` request... and fixes logging into the public idr (without a pre-existing session).
It's still probably not a super-well designed login approach.  but at least works
=> small fix to session creation

src/napari_omero/plugins/loaders.py, src/napari_omero/widgets/gateway.py, src/napari_omero/widgets/main.py, src/napari_omero/widgets/tree_model.py
Fixes a couple of issues from #9
- No filtering by default group or user
- Alphabetical ordering
- Also caches `childCount` so we don't have to request this from the server multiple times.
To test:
```
$ omero login
$ napari_omero
```
The biggest issue now is that we try to load the whole depth of the tree up-front, instead of waiting for the user to expand each node.
This means that with IDR, you are loading *forever* and never reach the whole tree. But the top of the tree loads OK:
=> Omero tree fixes

src/napari_omero/plugins/loaders.py
When loading OMERO image, instead of looping through Channels, getting metadata and lazy data for each in turn,
we now get the **5D** data (regardless of whether this is a multi-Z or multi-T image) and a single dict with `channel_axis:1`
This means that the data dimensions don't change and are consistent with the ome-zarr spec. Shape is `(t, c, z, y, x)`.
=> load_image_wrapper returns 5D data with channel_axis:1

src/napari_omero/plugins/loaders.py
This comments-out the setting of Z-scale, which I find causes various issues (testing with
`napari==0.3.5`).
Testing with a Z-stack image of `size_Z = 50`, with pixel size `X: 0.633` and `Z: 0.2` microns. Available at
https://downloads.openmicroscopy.org/images/DV/elena/P-TRE/P-TRE_21_R3D_D3D.dv
Without this PR, we set `scale = [1, 3.0161362196625654, 1, 1]`, which causes the Z-slider to report an index of Z-1.
See first screenshot:
- The max Z index is 48 (should be 49).
- The current index in the screenshot is showing as 0, when the slider has been incremented 1 place from the left. (left-most position also shows index of 0).
- `get_plane()` is correctly loading Z-index of 1 from OMERO. 
- If I then click to add a Shapes layer, the Z-index slider shows that I am now on index ```3 / …
```
=> Dont set z scale

src/napari_omero/utils.py
As reported https://github.com/tlambert03/napari-omero/pull/17#issuecomment-651589069 by @joshmoore 
This makes the omero plugin more specific about the paths that it tries to handle.
Only handle paths that match `Image|Dataset|Project:ID`.
Maybe this should only be `Image:ID` since we don't yet handle Dataset or Project.
To test:
- Open something that is not handled by other plugins, e.g regular zarr (not ome-zarr) 
```napari 1.zarr/masks/0/```  See https://github.com/tlambert03/napari-omero/pull/17#issuecomment-651588577
- Shouldn't see any error like:
```
08:59:04 ERROR PluginError: Error in plugin 'omero', hook 'napari_get_reader'
Cause was: NameError('No such Image: object #0 (::omero::RLong)\n{\n    _val = 0\n}',)
```
=> Omero plugin only handles path with Image:ID

environment.yml, setup.cfg, src/napari_omero/plugins/masks.py, src/napari_omero/plugins/omero.py
Some initial code to save napari labels to OMERO as masks.
Work in progress (needs linting, mypi types etc).
cc @joshmoore 
To test:
We use the ```omero napari``` command so that the "Save ROIs" button is displayed.
```
$ omero napari view Image:1
```
Draw some labels on the image.
Click "Save ROIs".
Each label should be saved as a new ROI with Mask shape(s)
=> save_rois() saves masks to OMERO

README.md
While testing for https://github.com/tlambert03/napari-omero/issues/36 on a new install, I noticed that `$ napari_omero` command didn't work and I needed `$ napari-omero`.
Don't know if something changed or has this always been wrong?
=> Fix napari-omero command in README

README.md
The contributing guide section was outdated, referring to an env.yml
omero-py still needs to come from conda-forge and we're limited to python 3.10 on the upper bound, so I use that in the new instructions.
=> Update README.md contributing guide

src/napari_omero/plugins/loaders.py
Closes: https://github.com/tlambert03/napari-omero/issues/60
I believe that at least with modern napari, this will also address the concerns from #15 
Given that there is no GUI for pushing Shapes yet, it's not easy to test that yet.
Below is an image of a OMERO added image with non-1 scales for ZYX.
You can see the dims and that when I create a shape and draw on it, the Shape data represents pixel space
=> ENH: Set layer scale from getPixelSizeX Y X

.github/workflows/ci.yml, README.md, pyproject.toml
As noted here: https://github.com/tlambert03/napari-omero/issues/82
zeroc-ice 3.6.5 on conda-forge supports up to python 3.12 now, so we can lift the restrictions.
This PR changes the metadata in pyproject, expands testing (3.9-3.12 on ubuntu, just top and bottom on macOS and windows), and updates the README.
At a minimum, once some iteration of this PR is released we will need to update the conda-forge recipe to change the python pin (https://github.com/conda-forge/napari-omero-feedstock/blob/07743f4ee515cd2762ea3d737102fd294102cf18/recipe/meta.yaml#L29)
=> [Maint] Allow python to up 3.12

src/napari_omero/widgets/main.py
Closes: https://github.com/tlambert03/napari-omero/issues/73
My understanding is that expanding items was triggering the `fetch` methods from the model, adding items to the tree. But it doesn't involve selection. And without selection, the thumbnails are not updated and become out of sync with the tree model.
Then, when you click on an item in the tree it sets the item in the model and the thumbnail grid. Both involve interactions with the Blitz gateway and I think this was creating some sort of race condition leading to the seg faults I observe.
Additionally, setting the thumbnail selection triggered `load_image`, as did selecting the item in the list.
I think the solution from #61 doesn't work anymore because the image loading from the thumbnail happens second, after the tree item …
=> Bugfix: Prevent double loading by having the tree model be a single source of truth

src/napari_omero/plugins/loaders.py
Closes https://github.com/tlambert03/napari-omero/issues/62
In this PR, the data array is checked for singleton dimensions that are not C (C is the channel_axis, so napari splits it and it's squeezed out). These non-C singletons are squeezed and then the `scale` and `axis_labels` are updated to account for the dropped dims.
Note I added `axis_labels` to the metadata, because it made implementing and testing this *much* easier!
I would open an image in omeroweb and the same image in napari and look at:
```
for layer in viewer.layers
print(layer.axis_labels, layer.data.shape, layer.scale)
```
This is a napari 0.5.0 and newer kwarg though, so we can drop it if we don't want to bump the min requirement.
Edit: I commented out the axis_labels usage so we don't break <0.5 with this minor …
=> Account for singleton dimensions, by squeezing them out and adjusting metadata accordingly

src/napari_omero/plugins/loaders.py
Closes: https://github.com/tlambert03/napari-omero/issues/77
Currently when an image is loaded the color from OMERO is used to create a new colormap every time.
In this PR I used a napari utility function that checks whether a colormap exists for the color and use that, else make a new colormap with the hex code of the color.
This works quite well for the images I've tested that use CYM, RGB. Nice QoL improvement.
I did run into an issue with White (which also happens for Black) where napari incorrectly doesn't realize it has that colormap (gray and gray_r) see https://github.com/napari/napari/issues/7504. I've put in a workaround.
=> ENH: Check OMERO color versus napari colormaps and use them if they exist

README.md
The existing instructions don't end up installing a Qt backend, which results in a warning and failure to launch, because napari package on conda no longer includes pyqt by default.
This PR clarifies the conda instructions to account for that.
=> Update README.md to emphasize conda install (Qt backend)

README.md
Fixes #89 
Added a small hint in the readme section that developers should watch out in their plugins when processing data from napari-OMERO. The hint tells them to make sure their plugins are dask-compatible if they want to use napari-OMERO in conjunction with their plugins.
=> Added hint for dask loading

src/napari_omero/plugins/loaders.py
This PR offers a simple solution to open OMERO images always as a `Image` layer, avoiding the error described in #91 .
=> Forces napari to always open images as Image layers

pyproject.toml, src/napari_omero/plugins/loaders.py
Fixes #16 
This pull request includes updates to the `pyproject.toml` file and the `load_image_wrapper` function in `src/napari_omero/plugins/loaders.py` to enhance functionality with OMERO. It might be a bit overkill to just add all the omero metadata but I feel like it's cleanest to stay close to the metadata standards OME already provides for us.
Dependency updates:
* [`pyproject.toml`](diffhunk://#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711R58): Added `omero-marshal` to the list of dependencies.
Functionality enhancements:
* [`src/napari_omero/plugins/loaders.py`](diffhunk://#diff-aff5e674ec54bcc0d4f442416df8ec684c314d7f2e8e1bf14e21b4561de9d1f9R102-R109): Updated the `load_image_wrapper` function to include JSON metadata encoding using `omero_marshal`.
=> Add omero metadata

src/napari_omero/plugins/loaders.py
This reverts commit 3bc011b727cf4c25152214d6f1bd51fb09b1b27b #90 
The idea is to restore the things to the OME model, which will also make the existing ROI upload work.
Then we will migrate to a napari>=0.5.0 approach using Layer.axis_labels.
For more insight, please see discussion started with: https://github.com/tlambert03/napari-omero/pull/100#issuecomment-2843233589
=> Revert "Account for singleton dimensions, by squeezing them out and adjusting metadata accordingly (#90)"

src/napari_omero/plugins/loaders.py
Fixes #71 
This should be a much simpler way to avoid widget crashes due to disconnect errors (e.g., through idle timeouts). The root issue here is that the `QGateway` itself doesn't check whether it's connected in `gateway.isConnected()`. Really checking this there would also be quite a nuisance as that would come with a timeout for the check itself - which in turn introduces quite a lag into the image loading.
To fix it, I added a `force_reconnect` option to the function that retrieves the gateway (`utils > get_gateway`) that brings up a `LoginForm`. If this is passed correctly (shouldn't be difficult for an idle timeout), then the image loading resumes normally. This functionality is invoked by a simple `try-except` block in the reader function that retrieves the `image_wrapper` …
=> Fix idle timeout

pyproject.toml, src/napari_omero/plugins/loaders.py
Relevant for #88:
This introduces a napari version pin of `>0.5.0` and sets the `axis_labels` property of images loaded from OMERO. This should make working with various dimensions a bit easier in the future.
=> Support named axes

src/napari_omero/plugins/loaders.py
Fixes #98 
This prepends the omero image id to the respective layer name of each channel. Especially for multiple iamges open at the same time, this should make things a bit easier 👍
=> prepend image id to layer

pyproject.toml
We no longer import from vispy, so it's not a direct dependency, so it doesn't belong in our dependencies list.
Further, napari will soon move up to 0.15 in 0.6.1, so the upper bound on the current pin is potentially problematic in terms of compatibility.
We will need a release with this change before/around the release of 0.6.1
=> Update pyproject.toml to not restrict vispy (drop it)
